/*
    PXG Faction Master Registry
    ----------------------------
    AUTO-GENERATED BY FBT GOVERNOR
    Last Update: 2026-04-20 19:27:20
*/

[
    //                        --BLUFOR--
    ["BLUFOR", "British Armed Forces", "Army", "Modern", "MTP"],
    ["BLUFOR", "British Armed Forces", "Army", "Modern", "Woodland"],
    ["BLUFOR", "British Armed Forces", "Royal Marines", "Modern", "Desert"],
    ["BLUFOR", "United States Military", "Army", "Modern", "Desert"],
    //                        --INDEP--
    ["INDEP", "United Nations", "Peacekeepers", "Modern", "Blue"],
    //                        --OPFOR--
    ["OPFOR", "Russian Armed Forces", "Army", "Modern", "Woodland"]
]
