/*
    PXG Faction Master Registry
    ----------------------------
    This is the Master Registry Proxy. It handles both static base factions
    and dynamic custom factions generated by the FBT Governor.
*/

private _factions = [
    //                        --BLUFOR--
    ["BLUFOR", "British Armed Forces", "Army", "Modern", "MTP"],
    ["BLUFOR", "British Armed Forces", "Royal Marines", "Modern", "Desert"],
    ["BLUFOR", "United States Military", "Army", "Modern", "Desert"],
    //                        --INDEP--
    ["INDEP", "United Nations", "Peacekeepers", "Modern", "Blue"],
    //                        --OPFOR--
    ["OPFOR", "Russian Armed Forces", "Army", "Modern", "Woodland"]
];

// --- DYNAMIC FBT HOOK ---
// This part pulls in your custom factions. If the file is missing, it skips safely.
private _fbtFile = "Scripts\Factions\FBT_Registry_Generated.sqf";
if (fileExists _fbtFile) then {
    private _custom = call compile preprocessFile _fbtFile;
    if (!isNil "_custom" && {_custom isEqualType []}) then {
        // Only append unique factions that aren't already in the base list
        {
            if !(_x in _factions) then { _factions pushBack _x; };
        } forEach _custom;
    };
};

_factions
