/*
    PXG_Export_Faction.sqf
    -------------------------------
    Serializes the master hashmap into a formatted SQF string and copies it to the clipboard.
*/

private _masterHash = missionNamespace getVariable ["PXG_Builder_MasterHash", createHashMap];
if (count _masterHash == 0) exitWith { systemChat "Error: No faction data found to export!"; };

// 1. Metadata
private _meta = _masterHash getOrDefault ["Metadata", createHashMap];
private _side = _meta getOrDefault ["Side", "BLUFOR"];
private _name = _meta getOrDefault ["FactionName", "PXG_Faction"];
private _camo = _meta getOrDefault ["Camo", "Desert"];
private _era  = _meta getOrDefault ["Era", "Modern"];

// 2. Formatting the Header
private _output = "/*" + endl;
_output = _output + "    PXG Faction Export: " + _name + endl;
_output = _output + "    Generated by PXG Faction Builder Tool" + endl;
_output = _output + "*/" + endl + endl;

// 3. Serializing the Hashmap (Pretty Printed)
private _hashStr = str _masterHash;

// Clean up the string to make it look like a definition
// SQF str on Hashmaps returns "[[Key, Value], [Key, Value]]" conceptually or similar.
// We want to make it look professional.

_output = _output + "private _factionData = " + _hashStr + ";" + endl + endl;
_output = _output + "// Paste this into your Faction Registration file." + endl;

// 4. Copy to Clipboard
copyToClipboard _output;

// 5. User Feedback
systemChat "Faction exported successfully! Data copied to your OS Clipboard.";
playSound "v_low_f";
uiSleep 0.1;
playSound "v_low_f";
