// Fonts
#define GUI_FONT_NORMAL			RobotoCondensed
#define GUI_FONT_BOLD			RobotoCondensedBold
#define GUI_FONT_THIN			RobotoCondensedLight
#define GUI_FONT_MONO			EtelkaMonospacePro
#define GUI_FONT_NARROW			EtelkaNarrowMediumPro
#define GUI_FONT_CODE			LucidaConsoleB
#define GUI_FONT_SYSTEM			TahomaB

// Grids
#define GUI_GRID_CENTER_WAbs		((safezoneW / safezoneH) min 1.2)
#define GUI_GRID_CENTER_HAbs		(GUI_GRID_CENTER_WAbs / 1.2)
#define GUI_GRID_CENTER_W		(GUI_GRID_CENTER_WAbs / 40)
#define GUI_GRID_CENTER_H		(GUI_GRID_CENTER_HAbs / 25)
#define GUI_GRID_CENTER_X		(safezoneX + (safezoneW - GUI_GRID_CENTER_WAbs)/2)
#define GUI_GRID_CENTER_Y		(safezoneY + (safezoneH - GUI_GRID_CENTER_HAbs)/2)

#define GUI_GRID_X	(0)
#define GUI_GRID_Y	(0)
#define GUI_GRID_W	(0.025)
#define GUI_GRID_H	(0.04)
#define GUI_GRID_WAbs	(1)
#define GUI_GRID_HAbs	(1)

// Armory Dialog IDCs
#define IDD_ARMORY 431234
#define IDC_ARMORY_SIDE 431500
#define IDC_ARMORY_FACTION_TREE 431501
#define IDC_ARMORY_LOADOUT_TREE 431503
#define IDC_ARMORY_CAMO_TEXT 431005
#define IDC_ARMORY_CAMO_LIST 431504
#define IDC_ARMORY_BACKGROUND 431006

// Resupply Dialog IDCs
#define IDD_RESUPPLY 451922
#define IDC_RESUPPLY_SIDE 451504
#define IDC_RESUPPLY_FACTION_TREE 451501
#define IDC_RESUPPLY_SUPPLIES_LB 451502
#define IDC_RESUPPLY_SPAWNPOINTS 451500
#define IDC_RESUPPLY_CONTENTS_TEXT 451505
#define IDC_RESUPPLY_CONTENTS_SPACE_TEXT 451506
#define IDC_RESUPPLY_CAMO_TEXT 451507
#define IDC_RESUPPLY_CAMO_LIST 451508
#define IDC_RESUPPLY_BACKGROUND 451006

// Motorpool Dialog IDCs
#define IDD_MOTORPOOL 461922
#define IDC_MOTORPOOL_SIDE 461504
#define IDC_MOTORPOOL_FACTION_TREE 461501
#define IDC_MOTORPOOL_VEHICLE_LB 461502
#define IDC_MOTORPOOL_SPAWNPOINTS 461500
#define IDC_MOTORPOOL_PREVIEW 461505
#define IDC_MOTORPOOL_CARGO_TEXT 461499
#define IDC_MOTORPOOL_SEATS_TEXT 461498
#define IDC_MOTORPOOL_CAMO_TEXT 461506
#define IDC_MOTORPOOL_CAMO_LIST 461507
#define IDC_MOTORPOOL_BACKGROUND 461006

// Config IDCs
#define IDC_UI_OPACITY_TOGGLE 400001
#define IDC_UI_ORBIT_TOGGLE 400002

// GUI Styling
#define GUI_COLOR_UI_GREY {0.7, 0.7, 0.7, 1}
#define GUI_STR_OPACITY "%"
#define GUI_STR_ORBIT "<"
#define GUI_W_BTN_S (0.03 * safezoneW)    // Small (Opacity/Orbit)
#define GUI_W_BTN_M (0.06 * safezoneW)    // Medium (Close/Spawn)
#define GUI_W_BTN_L (0.045 * safezoneW)   // Switch (Motorpool/Resupply)
#define GUI_H_BTN (0.02 * safezoneH)
