/*
    PXG Faction Core Configuration
    Generated via Pythia Governor
*/

private _factionData = createHashMapFromArray [
    ["MotorpoolSequence", createHashMapFromArray [
        ["UK3CB_BAF_MAN_HX58_Repair_Sand_MTP", "Utility Desert"],
        ["UK3CB_BAF_MAN_HX58_Cargo_Sand_A_MTP", "Utility Desert"],
        ["UK3CB_BAF_MAN_HX58_Transport_Sand_MTP", "Utility Desert"],
        ["UK3CB_BAF_LandRover_Soft_FFR_Sand_A_MTP", "Utility Desert"],
        ["UK3CB_BAF_LandRover_Amb_FFR_Sand_A_MTP", "Utility Desert"],
        ["UK3CB_BAF_MAN_HX58_Repair_Green_MTP", "Utility Woodland"],
        ["UK3CB_BAF_MAN_HX58_Cargo_Green_A_MTP", "Utility Woodland"],
        ["UK3CB_BAF_MAN_HX58_Transport_Green_MTP", "Utility Woodland"],
        ["UK3CB_BAF_LandRover_Soft_FFR_Green_A_MTP", "Utility Woodland"],
        ["UK3CB_BAF_LandRover_Amb_FFR_Green_A_MTP", "Utility Woodland"],
        ["UK3CB_BAF_LandRover_WMIK_HMG_FFR_Sand_A_MTP", "Armed Car/MRAP Desert"],
        ["UK3CB_BAF_LandRover_WMIK_Milan_FFR_Sand_A_MTP", "Armed Car/MRAP Desert"],
        ["UK3CB_BAF_Panther_GPMG_Sand_A_MTP", "Armed Car/MRAP Desert"],
        ["UK3CB_BAF_Husky_Passenger_HMG_Sand_MTP", "Armed Car/MRAP Desert"],
        ["UK3CB_BAF_Husky_Logistics_HMG_Sand_MTP", "Armed Car/MRAP Desert"],
        ["UK3CB_BAF_LandRover_WMIK_HMG_FFR_Green_A_MTP", "Armed Car/MRAP Woodland"],
        ["UK3CB_BAF_LandRover_WMIK_Milan_FFR_Green_A_MTP", "Armed Car/MRAP Woodland"],
        ["UK3CB_BAF_Panther_GPMG_Green_A_MTP", "Armed Car/MRAP Woodland"],
        ["UK3CB_BAF_Husky_Passenger_HMG_Green_MTP", "Armed Car/MRAP Woodland"],
        ["UK3CB_BAF_Husky_Logistics_HMG_Green_MTP", "Armed Car/MRAP Woodland"],
        ["UK3CB_BAF_FV432_Mk3_RWS_Sand_MTP", "APC Desert"],
        ["UK3CB_BAF_FV432_Mk3_RWS_Green_MTP", "APC Woodland"],
        ["UK3CB_BAF_Warrior_A3_D_Cage_Camo_MTP", "IFV Desert"],
        ["UK3CB_BAF_Warrior_A3_W_Cage_Camo_MTP", "IFV Woodland"],
        ["RHS_M119_D", "Artillery"],
        ["UK3CB_BAF_Merlin_HC3_18_GPMG_MTP", "Rotary Transport"],
        ["UK3CB_BAF_Chinook_HC2_MTP", "Rotary Transport"],
        ["UK3CB_BAF_Chinook_HC2_cargo_MTP", "Rotary Transport"],
        ["UK3CB_BAF_Apache_AH1_Generic_MTP", "Rotary Attack"],
        ["UK3CB_BAF_Hercules_C4_MTP", "Fixed Wing Transport"],
        ["UK3CB_BAF_Hercules_C4_cargo_MTP", "Fixed Wing Transport"],
        ["UK3CB_BAF_MQ9_Reaper_MTP", "Fixed Wing Attack"],
        ["UK3CB_BAF_RHIB_HMG_MTP", "Boat"],
        ["B_Boat_Transport_01_F", "Boat"],
        ["B_SDV_01_F", "Boat"],
        ["UK3CB_KRG_B_Quadbike", "Misc."],
        ["UK3CB_BAF_LandRover_Panama_Sand_A_MTP", "Misc."],
        ["UK3CB_BAF_LandRover_Panama_Green_A_MTP", "Misc."],
        ["UK3CB_BAF_MAN_HX58_Container_Sand", "Misc."],
        ["UK3CB_BAF_MAN_HX58_Container_Green", "Misc."]
    ]],
    ["ArmoryRoles", [["Platoon Lead", "Logistics", "Platoon Medic", "TACP"], ["Squad Lead", "Combat Medic", "Combat Engineer", "LAT Rifleman", "Pointman", "Grenadier", "Light Mortarman", "Automatic Rifleman", "Asst. Rifleman"], ["SF Lead", "Combat Medic", "Designated Marksman", "Explosives Specialist"], ["Recon Lead", "Sniper", "Anti-Material Rifleman", "Drone Operator"], ["MMG Lead", "MMG Gunner"], ["HMG Lead", "HMG Gunner"], ["HAT Lead", "HAT Gunner"], ["AA Lead", "AA Gunner"], ["Mortar Lead", "Mortar Gunner"], ["Crew Commander", "Crewman"], ["Rotary Pilot", "Fixed-Wing Pilot"]]],
    ["Resupply", []],
    ["Armory", createHashMapFromArray [
        ["sqd_ld", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_C"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sqd_eng", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_D"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Sapper_L_A"]
    ]],
        ["rcn_drone", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_Silencer_L85", "UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_Ghillie_RM"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Net_A"],
        ["ITEMS", ["DRNP_AR2P", "ACE_HuntIR_monitor", "ACE_UAVBattery", "ACE_UAVBattery", "ACE_UAVBattery"]],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["sup_mor_l", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_F"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "I_Mortar_01_support_F"]
    ]],
        ["ar_c", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L22A2", []]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_CrewHelmet_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["r_pil", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L22A2", []]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Belt_A"],
        ["UNIFORM", "UK3CB_BAF_U_HeliPilotCoveralls_Army"],
        ["HEADGEAR", "H_Cap_headphones"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "None"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["plt_med", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Medic_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Medic_L_B"]
    ]],
        ["sqd_aar", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_C"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sup_mmg_l", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_F"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sup_hat_g", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["UK3CB_BAF_Javelin_Slung_Tube", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", "UK3CB_BAF_Javelin_CLU"],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_H_B"]
    ]],
        ["MotorpoolSequence", createHashMapFromArray [
        ["UK3CB_BAF_MQ9_Reaper_MTP", "Fixed Wing Attack"],
        ["B_SDV_01_F", "Boat"],
        ["UK3CB_BAF_Husky_Logistics_HMG_Sand_MTP", "Armed Car/MRAP Desert"],
        ["UK3CB_BAF_Warrior_A3_W_Cage_Camo_MTP", "IFV Woodland"],
        ["UK3CB_BAF_Husky_Passenger_HMG_Green_MTP", "Armed Car/MRAP Woodland"],
        ["UK3CB_BAF_FV432_Mk3_RWS_Sand_MTP", "APC Desert"],
        ["UK3CB_BAF_LandRover_Amb_FFR_Sand_A_MTP", "Utility Desert"],
        ["UK3CB_BAF_LandRover_WMIK_Milan_FFR_Sand_A_MTP", "Armed Car/MRAP Desert"],
        ["UK3CB_BAF_Panther_GPMG_Green_A_MTP", "Armed Car/MRAP Woodland"],
        ["UK3CB_BAF_Merlin_HC3_18_GPMG_MTP", "Rotary Transport"],
        ["UK3CB_BAF_Husky_Passenger_HMG_Sand_MTP", "Armed Car/MRAP Desert"],
        ["UK3CB_BAF_Chinook_HC2_cargo_MTP", "Rotary Transport"],
        ["UK3CB_BAF_MAN_HX58_Repair_Green_MTP", "Utility Woodland"],
        ["UK3CB_BAF_FV432_Mk3_RWS_Green_MTP", "APC Woodland"],
        ["UK3CB_BAF_LandRover_Panama_Sand_A_MTP", "Misc."],
        ["UK3CB_BAF_LandRover_Soft_FFR_Green_A_MTP", "Utility Woodland"],
        ["UK3CB_BAF_LandRover_Amb_FFR_Green_A_MTP", "Utility Woodland"],
        ["UK3CB_BAF_LandRover_WMIK_HMG_FFR_Sand_A_MTP", "Armed Car/MRAP Desert"],
        ["UK3CB_BAF_Husky_Logistics_HMG_Green_MTP", "Armed Car/MRAP Woodland"],
        ["UK3CB_BAF_LandRover_Panama_Green_A_MTP", "Misc."],
        ["UK3CB_BAF_LandRover_WMIK_HMG_FFR_Green_A_MTP", "Armed Car/MRAP Woodland"],
        ["UK3CB_BAF_LandRover_WMIK_Milan_FFR_Green_A_MTP", "Armed Car/MRAP Woodland"],
        ["UK3CB_BAF_MAN_HX58_Repair_Sand_MTP", "Utility Desert"],
        ["UK3CB_BAF_MAN_HX58_Cargo_Green_A_MTP", "Utility Woodland"],
        ["UK3CB_BAF_Hercules_C4_MTP", "Fixed Wing Transport"],
        ["UK3CB_BAF_Hercules_C4_cargo_MTP", "Fixed Wing Transport"],
        ["UK3CB_BAF_MAN_HX58_Container_Green", "Misc."],
        ["UK3CB_BAF_Warrior_A3_D_Cage_Camo_MTP", "IFV Desert"],
        ["UK3CB_BAF_Chinook_HC2_MTP", "Rotary Transport"],
        ["UK3CB_BAF_Apache_AH1_Generic_MTP", "Rotary Attack"],
        ["UK3CB_KRG_B_Quadbike", "Misc."],
        ["UK3CB_BAF_MAN_HX58_Transport_Sand_MTP", "Utility Desert"],
        ["B_Boat_Transport_01_F", "Boat"],
        ["UK3CB_BAF_MAN_HX58_Cargo_Sand_A_MTP", "Utility Desert"],
        ["UK3CB_BAF_LandRover_Soft_FFR_Sand_A_MTP", "Utility Desert"],
        ["UK3CB_BAF_MAN_HX58_Transport_Green_MTP", "Utility Woodland"],
        ["UK3CB_BAF_RHIB_HMG_MTP", "Boat"],
        ["UK3CB_BAF_Panther_GPMG_Sand_A_MTP", "Armed Car/MRAP Desert"],
        ["RHS_M119_D", "Artillery"],
        ["UK3CB_BAF_MAN_HX58_Container_Sand", "Misc."]
    ]],
        ["ArmoryRoles", [["Platoon Lead", "Logistics", "Platoon Medic", "TACP"], ["Squad Lead", "Combat Medic", "Combat Engineer", "LAT Rifleman", "Pointman", "Grenadier", "Light Mortarman", "Automatic Rifleman", "Asst. Rifleman"], ["SF Lead", "Combat Medic", "Designated Marksman", "Explosives Specialist"], ["Recon Lead", "Sniper", "Anti-Material Rifleman", "Drone Operator"], ["MMG Lead", "MMG Gunner"], ["HMG Lead", "HMG Gunner"], ["HAT Lead", "HAT Gunner"], ["AA Lead", "AA Gunner"], ["Mortar Lead", "Mortar Gunner"], ["Crew Commander", "Crewman"], ["Rotary Pilot", "Fixed-Wing Pilot"]]],
        ["tacp", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_B"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_JTAC_L_A"]
    ]],
        ["rcn_amr", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L135A1", ["rhsusf_acc_M8541"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_Ghillie_RM"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Net_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["sup_hmg_l", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "RHS_M2_Tripod_Bag"]
    ]],
        ["Resupply", []],
        ["ar_ld", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L22A2", []]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_CrewHelmet_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["Armory", createHashMapFromArray [
        ["sqd_ld", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sqd_eng", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Sapper_L_A"]
    ]],
        ["rcn_drone", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_Silencer_L85", "UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_Ghillie_RM"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Net_A"],
        ["ITEMS", ["DRNP_AR2P", "ACE_HuntIR_monitor", "ACE_UAVBattery", "ACE_UAVBattery", "ACE_UAVBattery"]],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["sup_mor_l", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_F"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "I_Mortar_01_support_F"]
    ]],
        ["ar_c", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L22A2", []]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_CrewHelmet_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["r_pil", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L22A2", []]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Belt_A"],
        ["UNIFORM", "UK3CB_BAF_U_HeliPilotCoveralls_Army"],
        ["HEADGEAR", "H_Cap_headphones"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "None"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["plt_med", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Medic_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Medic_L_B"]
    ]],
        ["sqd_aar", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_C"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sup_mmg_l", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_C"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sup_hat_g", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["UK3CB_BAF_Javelin_Slung_Tube", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_C"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", "UK3CB_BAF_Javelin_CLU"],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_H_B"]
    ]],
        ["tacp", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_B"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_JTAC_L_A"]
    ]],
        ["rcn_amr", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L135A1", ["rhsusf_acc_M8541"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_Ghillie_RM"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Net_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["sup_hmg_l", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_D"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "RHS_M2_Tripod_Bag"]
    ]],
        ["ar_ld", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L22A2", []]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_CrewHelmet_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["sf_ld", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L119A1_UKUGL", ["UK3CB_BAF_Silencer_L85", "UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Scrim_B"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sqd_lat", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["UK3CB_BAF_NLAW_Launcher", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_B"],
        ["ITEMS", ["UK3CB_BAF_NLAW_Launcher"]],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sqd_gre", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Grenadier_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_E"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["rcn_ld", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_Silencer_L85", "UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_Ghillie_RM"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Net_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["sup_mor_g", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_F"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "I_Mortar_01_weapon_F"]
    ]],
        ["sqd_med", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Medic_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_D"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Medic_L_B"]
    ]],
        ["sf_dmr", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L129A1", ["UK3CB_BAF_Silencer_L115A3", "UK3CB_BAF_LLM_IR_Black", "UK3CB_BAF_TA648", "UK3CB_underbarrel_acc_fgrip_bipod"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Scrim_E"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sup_aa_g", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["rhs_weap_fim92", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_B"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_H_B"]
    ]],
        ["sqd_ar", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L110A3", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_EOT552"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_MG_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_C"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sf_med", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L110A3", ["UK3CB_BAF_Silencer_L110", "UK3CB_BAF_LLM_IR_Black", "RKSL_optic_EOT552"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Medic_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Scrim_E"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Medic_L_B"]
    ]],
        ["sqd_hgre", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["UK3CB_BAF_M6", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_A"],
        ["ITEMS", ["UK3CB_BAF_L16_RangeTable"]],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sf_eng", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["UK3CB_BAF_NLAW_Launcher", []]],
        ["PRIMARY", ["UK3CB_BAF_L119A1_RIS", ["UK3CB_BAF_Silencer_L85", "UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS", "UK3CB_underbarrel_acc_grippod"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Scrim_C"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sup_mmg_g", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L7A2", []]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_MG_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_D"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["rcn_sni", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L115A3_Ghillie", ["UK3CB_BAF_Silencer_L115A3", "rhsusf_acc_M8541", "UK3CB_underbarrel_acc_bipod"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_Ghillie_RM"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Net_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["sup_hat_l", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["UK3CB_BAF_Javelin_Slung_Tube", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_F"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_H_B"]
    ]],
        ["sup_aa_l", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_E"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_H_B"]
    ]],
        ["f_pil", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L22A2", []]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_V_Invisible"],
        ["UNIFORM", "U_B_PilotCoveralls"],
        ["HEADGEAR", ""],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "None"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["sup_hmg_g", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_E"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "RHS_M2_Gun_Bag"]
    ]],
        ["plt", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_B"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["logi", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_C"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Engineer_L_A"]
    ]],
        ["sqd_brc", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L128A1", ["RKSL_optic_EOT552"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_D"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_PointMan_L_A"]
    ]]
    ]],
        ["ArmoryIDs", [["plt", "logi", "plt_med", "tacp"], ["sqd_ld", "sqd_med", "sqd_eng", "sqd_lat", "sqd_brc", "sqd_gre", "sqd_hgre", "sqd_ar", "sqd_aar"], ["sf_ld", "sf_med", "sf_dmr", "sf_eng"], ["rcn_ld", "rcn_sni", "rcn_amr", "rcn_drone"], ["sup_mmg_l", "sup_mmg_g"], ["sup_hmg_l", "sup_hmg_g"], ["sup_hat_l", "sup_hat_g"], ["sup_aa_l", "sup_aa_g"], ["sup_mor_l", "sup_mor_g"], ["ar_ld", "ar_c"], ["r_pil", "f_pil"]]],
        ["sf_ld", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L119A1_UKUGL", ["UK3CB_BAF_Silencer_L85", "UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Scrim_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sqd_lat", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["UK3CB_BAF_NLAW_Launcher", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_A"],
        ["ITEMS", ["UK3CB_BAF_NLAW_Launcher"]],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sqd_gre", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Grenadier_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_B"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["rcn_ld", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_Silencer_L85", "UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_Ghillie_RM"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Net_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["sup_mor_g", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_E"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "I_Mortar_01_weapon_F"]
    ]],
        ["sqd_med", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Medic_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_F"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Medic_L_B"]
    ]],
        ["sf_dmr", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L129A1", ["UK3CB_BAF_Silencer_L115A3", "UK3CB_BAF_LLM_IR_Black", "UK3CB_BAF_TA648", "UK3CB_underbarrel_acc_fgrip_bipod"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Scrim_F"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sup_aa_g", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["rhs_weap_fim92", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_C"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_H_B"]
    ]],
        ["sqd_ar", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L110A3", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_EOT552"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_MG_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_C"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sf_med", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L110A3", ["UK3CB_BAF_Silencer_L110", "UK3CB_BAF_LLM_IR_Black", "RKSL_optic_EOT552"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Medic_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Scrim_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Medic_L_B"]
    ]],
        ["Motorpool", []],
        ["ArmoryGroups", ["Platoon HQ", "Squad", "Special Forces", "Recon", "Support MMG", "Support HMG", "Support HAT", "Support AA", "Support Mortar", "Cavalry", "Air Cavalry"]],
        ["sqd_hgre", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["UK3CB_BAF_M6", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_A"],
        ["ITEMS", ["UK3CB_BAF_L16_RangeTable"]],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sf_eng", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["UK3CB_BAF_NLAW_Launcher", []]],
        ["PRIMARY", ["UK3CB_BAF_L119A1_RIS", ["UK3CB_BAF_Silencer_L85", "UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS", "UK3CB_underbarrel_acc_grippod"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Scrim_C"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["sup_mmg_g", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L7A2", []]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_MG_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_C"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["rcn_sni", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L115A3_Ghillie", ["UK3CB_BAF_Silencer_L115A3", "rhsusf_acc_M8541", "UK3CB_underbarrel_acc_bipod"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_Ghillie_RM"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Net_A"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["sup_hat_l", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["UK3CB_BAF_Javelin_Slung_Tube", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_E"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_H_B"]
    ]],
        ["ArmorySequence", [["plt", "Platoon Lead", "Platoon HQ"], ["logi", "Logistics", "Platoon HQ"], ["plt_med", "Platoon Medic", "Platoon HQ"], ["tacp", "TACP", "Platoon HQ"], ["sqd_ld", "Squad Lead", "Squad"], ["sqd_med", "Combat Medic", "Squad"], ["sqd_eng", "Combat Engineer", "Squad"], ["sqd_lat", "LAT Rifleman", "Squad"], ["sqd_brc", "Pointman", "Squad"], ["sqd_gre", "Grenadier", "Squad"], ["sqd_hgre", "Light Mortarman", "Squad"], ["sqd_ar", "Automatic Rifleman", "Squad"], ["sqd_aar", "Asst. Rifleman", "Squad"], ["sf_ld", "SF Lead", "Special Forces"], ["sf_med", "Combat Medic", "Special Forces"], ["sf_dmr", "Designated Marksman", "Special Forces"], ["sf_eng", "Explosives Specialist", "Special Forces"], ["rcn_ld", "Recon Lead", "Recon"], ["rcn_sni", "Sniper", "Recon"], ["rcn_amr", "Anti-Material Rifleman", "Recon"], ["rcn_drone", "Drone Operator", "Recon"], ["sup_mmg_l", "MMG Lead", "Support MMG"], ["sup_mmg_g", "MMG Gunner", "Support MMG"], ["sup_hmg_l", "HMG Lead", "Support HMG"], ["sup_hmg_g", "HMG Gunner", "Support HMG"], ["sup_hat_l", "HAT Lead", "Support HAT"], ["sup_hat_g", "HAT Gunner", "Support HAT"], ["sup_aa_l", "AA Lead", "Support AA"], ["sup_aa_g", "AA Gunner", "Support AA"], ["sup_mor_l", "Mortar Lead", "Support Mortar"], ["sup_mor_g", "Mortar Gunner", "Support Mortar"], ["ar_ld", "Crew Commander", "Cavalry"], ["ar_c", "Crewman", "Cavalry"], ["r_pil", "Rotary Pilot", "Air Cavalry"], ["f_pil", "Fixed-Wing Pilot", "Air Cavalry"]]],
        ["sup_aa_l", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_F"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_H_B"]
    ]],
        ["f_pil", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L22A2", []]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_V_Invisible"],
        ["UNIFORM", "U_B_PilotCoveralls"],
        ["HEADGEAR", ""],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "None"],
        ["BACKPACK", "UK3CB_B_Invisible"]
    ]],
        ["sup_hmg_g", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_F"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "RHS_M2_Gun_Bag"]
    ]],
        ["plt", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_UGL", ["UK3CB_BAF_LLM_IR_Black", "RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_F"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D"]
    ]],
        ["logi", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L85A2_EMAG", ["RKSL_optic_LDS"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_SL_C"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_B"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_Engineer_L_A"]
    ]],
        ["sqd_brc", createHashMapFromArray [
        ["MAGAZINES", []],
        ["LAUNCHER", ["", []]],
        ["PRIMARY", ["UK3CB_BAF_L128A1", ["RKSL_optic_EOT552"]]],
        ["NVG", "UK3CB_BAF_HMNVS"],
        ["VEST", "UK3CB_BAF_V_Osprey_Rifleman_B"],
        ["UNIFORM", "UK3CB_BAF_U_CombatUniform_MTP"],
        ["HEADGEAR", "UK3CB_BAF_H_Mk7_Camo_C"],
        ["ITEMS", []],
        ["HANDGUN", ["UK3CB_BAF_L131A1", []]],
        ["BINOC", ""],
        ["GOGGLES", "G_Tactical_Clear"],
        ["BACKPACK", "UK3CB_BAF_B_Bergen_MTP_PointMan_L_A"]
    ]]
    ]],
    ["ArmoryIDs", [["plt", "logi", "plt_med", "tacp"], ["sqd_ld", "sqd_med", "sqd_eng", "sqd_lat", "sqd_brc", "sqd_gre", "sqd_hgre", "sqd_ar", "sqd_aar"], ["sf_ld", "sf_med", "sf_dmr", "sf_eng"], ["rcn_ld", "rcn_sni", "rcn_amr", "rcn_drone"], ["sup_mmg_l", "sup_mmg_g"], ["sup_hmg_l", "sup_hmg_g"], ["sup_hat_l", "sup_hat_g"], ["sup_aa_l", "sup_aa_g"], ["sup_mor_l", "sup_mor_g"], ["ar_ld", "ar_c"], ["r_pil", "f_pil"]]],
    ["Metadata", createHashMapFromArray [
        ["Side", "BLUFOR"],
        ["FactionName", "British Armed Forces"],
        ["Camo", "winter"],
        ["Era", "Modern"],
        ["Subfaction", "Army"]
    ]],
    ["Motorpool", []],
    ["ArmoryGroups", ["Platoon HQ", "Squad", "Special Forces", "Recon", "Support MMG", "Support HMG", "Support HAT", "Support AA", "Support Mortar", "Cavalry", "Air Cavalry"]],
    ["ArmorySequence", [["plt", "Platoon Lead", "Platoon HQ"], ["logi", "Logistics", "Platoon HQ"], ["plt_med", "Platoon Medic", "Platoon HQ"], ["tacp", "TACP", "Platoon HQ"], ["sqd_ld", "Squad Lead", "Squad"], ["sqd_med", "Combat Medic", "Squad"], ["sqd_eng", "Combat Engineer", "Squad"], ["sqd_lat", "LAT Rifleman", "Squad"], ["sqd_brc", "Pointman", "Squad"], ["sqd_gre", "Grenadier", "Squad"], ["sqd_hgre", "Light Mortarman", "Squad"], ["sqd_ar", "Automatic Rifleman", "Squad"], ["sqd_aar", "Asst. Rifleman", "Squad"], ["sf_ld", "SF Lead", "Special Forces"], ["sf_med", "Combat Medic", "Special Forces"], ["sf_dmr", "Designated Marksman", "Special Forces"], ["sf_eng", "Explosives Specialist", "Special Forces"], ["rcn_ld", "Recon Lead", "Recon"], ["rcn_sni", "Sniper", "Recon"], ["rcn_amr", "Anti-Material Rifleman", "Recon"], ["rcn_drone", "Drone Operator", "Recon"], ["sup_mmg_l", "MMG Lead", "Support MMG"], ["sup_mmg_g", "MMG Gunner", "Support MMG"], ["sup_hmg_l", "HMG Lead", "Support HMG"], ["sup_hmg_g", "HMG Gunner", "Support HMG"], ["sup_hat_l", "HAT Lead", "Support HAT"], ["sup_hat_g", "HAT Gunner", "Support HAT"], ["sup_aa_l", "AA Lead", "Support AA"], ["sup_aa_g", "AA Gunner", "Support AA"], ["sup_mor_l", "Mortar Lead", "Support Mortar"], ["sup_mor_g", "Mortar Gunner", "Support Mortar"], ["ar_ld", "Crew Commander", "Cavalry"], ["ar_c", "Crewman", "Cavalry"], ["r_pil", "Rotary Pilot", "Air Cavalry"], ["f_pil", "Fixed-Wing Pilot", "Air Cavalry"]]]
];

_factionData
